### ISSUE TITLE
docs: filter

### ISSUE THREAD

**Issue by wenfengwang** [vanus-labs/docs#110]
## Documentation

Please answer these questions before submitting your issue. Thanks!

### 1. What kind of enhancement do you need to improve Vanus documentation? (Required)

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [ ] Update inappropriate or misunderstanding content
- [x] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents

### 2. Tell us more about enhancement you need (Required)
Teach developers how to use Subscription filter.

### 3. Are you willing to solve this issue?
No

**Comment by xdlbdy** [comment]
#115
