### ISSUE TITLE
[Good First Issues]: review Vanus Documentation

### ISSUE THREAD

**Issue by JieDing** [vanus-labs/docs#124]
# Motivation

The best way to learn about an open-source project starts from reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

# Details

You can improve the quality of documentations from different ways.

No matter there are typos or format errors(punctuation, space, indentation, code block, etc.), or you simply find some content doesn't make sense, or you didn't get expected output after running some commands ,as long as you'd like to solve them, please join us to make docs better.

## Task List
- [x] #198 

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

# How to claim to solve the issue
If you want to solve a specific issue, please leave a comment in that issue like:

> I'd like to solve this issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by yashchaddha** [comment]
Hi @JieDing can i please get assigned to this issue, as i would like to contribute on this and start my OSC journey

**Comment by Hajer3349** [comment]
Hi @JieDing, is this issue still open? if it is then I would like to be assigned to it, thank you
